services:
  node-app:
    image: ghcr.io/zag-prj/zag-frontend:latest
    container_name: zad-frontend
    environment:
      - PORT=${NODE_PORT}   # Sets the environment variable for the container
    ports:
      - "${NODE_PORT}:${NODE_PORT}" # Maps the container's port to the host
    restart: unless-stopped

  asp-app:
    image: ghcr.io/zag-prj/zag-backend:latest
    container_name: zad-backend
    environment:
      - ASP_PORT=${ASP_PORT}           # Set ASP.NET environment variable
      - POSTGRES_HOST=${POSTGRES_HOST}  # Set the PostgreSQL host
      - POSTGRES_PORT=5432  # Set the PostgreSQL port
      - POSTGRES_USER=${POSTGRES_USER}  # Set PostgreSQL user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Set PostgreSQL password
      - POSTGRES_DB=${POSTGRES_DB}      # Set PostgreSQL database name
    ports:
      - "${ASP_PORT}:${ASP_PORT}"       # Maps the container's port to the host
    restart: never

  postgres:
    image: docker.io/postgres:latest
    container_name: zad-datalayer
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Set PostgreSQL password
      - POSTGRES_USER=${POSTGRES_USER}          # Set PostgreSQL user
      - POSTGRES_DB=${POSTGRES_DB}              # Set PostgreSQL database name
    ports:
      - "${POSTGRES_PORT}:5432"  # Exposes PostgreSQL port for access from the host
    restart: unless-stopped
