services:
  node-app:
    image: ghcr.io/tropicsatern36/zag-frontend:latest
    container_name: zad-frontend
    environment:
      - PORT=${NODE_PORT}   # Sets the environment variable for the container
    ports:
      - ${NODE_PORT}:${NODE_PORT} # Maps port 8080 of the container to port 8080 on the host
    restart: unless-stopped
  asp-app:
    image: ghcr.io/tropicsatern36/zag-backend:latest
    container_name: zad-backend
    #restart: unless-stopped
    restart: never
  postgres:
    image: docker.io/postgres:latest
    container_name: zad-datalayer
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432 # for asses from host machine. Testing only
    restart: unless-stopped
